name: "Docs Check"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"

jobs:
  docs:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/src/"

    - name: Commit documentation changes
      run: |
        git clone https://github.com/MolSSI/mmic_util.git
        cp -r docs/src/_build/html/* docs/
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
	github_token: ${{ secrets.GITHUB_TOKEN }}
